name: Build macOS Binary

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '13.0'  # Specify the Xcode version you need

    - name: Build macOS Binary
      run: |
        xcodebuild \
          -workspace Clipboard.xcworkspace \  # Specify your Xcode workspace
          -scheme Clipboard History \                   # Specify your Xcode scheme
          -configuration Release \               # Use Release configuration
          -destination "platform=macOS" \       # Specify the target platform
          build

