name: Build macOS Binary

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'  # Specify the Xcode version you need

    - name: List
      run: |
        xcodebuild -list
    - name: Build macOS Binary
      run: |
        xcodebuild build
